### ISSUE TITLE
Add support for AlmaLinux

### ISSUE THREAD

**Issue by vandah** [robertdebock/ansible-role-powertools#1]
## Proposed feature

Add support for AlmaLinux.

## Additional context

https://github.com/robertdebock/ansible-role-powertools/blob/a00c1645daa95e2bc67488ac363306b15fe93768/tasks/main.yml#L14

This should either include AlmaLinux or it can be solved by checking the `ansible_os_family` instead. (AlmaLinux is in the `RedHat` family)

**Comment by robertdebock** [comment]
Hi,

I'm sorry I missed this issue, especially, because a more recent issue and PR have been processed.

Good news; the role now supports AlmaLinux.
